imports:
    - { resource: 'b2b_flow_checkout/transition_definitions.yml' }
    - { resource: 'b2b_flow_checkout/transitions.yml' }
    - { resource: 'b2b_flow_checkout/steps.yml' }
    - { resource: 'b2b_flow_checkout/attributes.yml' }
