api:
    entities:
        Oro\Bundle\OrderBundle\Entity\Order:
            documentation_resource: '@OroOrderBundle/Resources/doc/api/order.md'
            form_event_subscriber:
                - oro_order.form.type.event_listener.subtotals_subscriber
                - oro_website.form_subscriber.default_website
            fields:
                paymentTerm:
                    property_path: payment_term_7c4f1e8e
                source:
                    data_type: nestedAssociation
                    fields:
                        __class__:
                            property_path: sourceEntityClass
                        id:
                            property_path: sourceEntityId
            actions:
                create:
                    fields:
                        subtotalValue:
                            exclude: true
                        totalValue:
                            exclude: true
                        totalDiscountsAmount:
                            exclude: true
                        internalStatus:
                            exclude: true

                update:
                    fields:
                        subtotalValue:
                            exclude: true
                        totalValue:
                            exclude: true
                        totalDiscountsAmount:
                            exclude: true
                        currency:
                            exclude: true
                        internalStatus:
                            exclude: true

        Extend\Entity\EV_Order_Internal_Status:
            actions: false

        Oro\Bundle\OrderBundle\Entity\OrderLineItem:
            documentation_resource: '@OroOrderBundle/Resources/doc/api/order_line_item.md'
            fields:
                value:
                    form_options:
                        mapped: false
                currency:
                    form_options:
                        mapped: false
            actions:
                create:
                    fields:
                        productUnitCode:
                            exclude: true
                update:
                    fields:
                        productUnitCode:
                            exclude: true
                delete: false
                delete_list: false
            subresources:
                order:
                    actions:
                        update_relationship: false

        Oro\Bundle\OrderBundle\Entity\OrderAddress:
            documentation_resource: '@OroOrderBundle/Resources/doc/api/order_address.md'
            fields:
                createdAt:
                    property_path: created
                updatedAt:
                    property_path: updated
                customRegion:
                    exclude: false # set manually because this field is marked as excluded in entity.yml
                    property_path: regionText
            subresources:
                country:
                    actions:
                        update_relationship: false
                region:
                    actions:
                        update_relationship: false

        Oro\Bundle\OrderBundle\Entity\OrderDiscount:
            documentation_resource: '@OroOrderBundle/Resources/doc/api/order_discount.md'

        Oro\Bundle\OrderBundle\Entity\OrderShippingTracking:
            documentation_resource: '@OroOrderBundle/Resources/doc/api/order_shipping_tracking.md'
