placeholders:
    placeholders:
        product_index_sidebar:
            items:
                product_sidebar_price_list_selector: ~
        oro_product_quick_add_additional_fields:
            items:
                quick_add_subtotal: ~
    items:
        product_sidebar_price_list_selector:
            action: OroPricingBundle:Product:sidebar
            applicable: "@oro_featuretoggle.checker.feature_checker->isFeatureEnabled('oro_price_lists')"
        quick_add_subtotal:
            template: OroPricingBundle:Product:subtotal.html.twig
