services:
    oro_order.api.form_listener.discount:
        class: 'Oro\Bundle\OrderBundle\Api\Form\EventListener\DiscountListener'
        public: true
        arguments:
            - '@oro_order.order.total.total_helper'

    oro_order.api.product_provider.sku_cached:
        class: 'Oro\Bundle\OrderBundle\Provider\SkuCachedProductProvider'
        public: false
        arguments:
            - '@oro_product.repository.product'

    oro_order.api.frontend.order_line_item_query_modifier:
        class: Oro\Bundle\OrderBundle\Api\OrderLineItemQueryModifier
        arguments:
            - '@oro_entity.orm.entity_class_resolver'
        tags:
            - { name: oro.api.query_modifier, requestType: frontend }

    oro_order.api.frontend.order_address_query_modifier:
        class: Oro\Bundle\OrderBundle\Api\OrderAddressQueryModifier
        arguments:
            - '@oro_entity.orm.entity_class_resolver'
        tags:
            - { name: oro.api.query_modifier, requestType: frontend }

    oro_order.api.handle_order_included_data:
        class: 'Oro\Bundle\OrderBundle\Api\Processor\HandleOrderIncludedData'
        arguments:
            - '@oro_order.api.product_provider.sku_cached'
        tags:
            - { name: oro.api.processor, action: create, group: load_data, priority: -40, class: '%oro_order.entity.order.class%' }
            - { name: oro.api.processor, action: update, group: load_data, priority: -40, class: '%oro_order.entity.order.class%' }

    oro_order.api.set_price_by_value_and_currency:
        class: 'Oro\Bundle\CurrencyBundle\Api\Processor\SetPriceByValueAndCurrency'
        tags:
            - { name: oro.api.processor, action: update, group: load_data, priority: -50, class: '%oro_order.entity.order_line_item.class%' }
            - { name: oro.api.processor, action: create, group: load_data, priority: -50, class: '%oro_order.entity.order_line_item.class%' }

    oro_order.api.update_request_data_for_order_line_item:
        class: 'Oro\Bundle\OrderBundle\Api\Processor\UpdateRequestDataForOrderLineItem'
        arguments:
            - '@oro_order.api.product_provider.sku_cached'
        tags:
            - { name: oro.api.processor, action: create, group: load_data, priority: -255, class: '%oro_order.entity.order_line_item.class%' }
            - { name: oro.api.processor, action: update, group: load_data, priority: -255, class: '%oro_order.entity.order_line_item.class%' }

    oro_order.api.compute_order_payment_status:
        class: Oro\Bundle\OrderBundle\Api\Processor\ComputeOrderPaymentStatus
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_payment.formatter.payment_status_label'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, collection: true, requestType: frontend, class: '%oro_order.entity.order.class%' }

    oro_order.api.compute_order_payment_method:
        class: Oro\Bundle\OrderBundle\Api\Processor\ComputeOrderPaymentMethod
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_payment.formatter.payment_method_label'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, collection: true, requestType: frontend, class: '%oro_order.entity.order.class%' }

    oro_order.api.compute_order_shipping:
        class: Oro\Bundle\OrderBundle\Api\Processor\ComputeOrderShipping
        arguments:
            - '@?oro_shipping.translator.shipping_method_label'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, class: '%oro_order.entity.order.class%' }

    oro_order.api.set_order_default_discount_type:
        class: Oro\Bundle\OrderBundle\Api\Processor\SetOrderDefaultDiscountType
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, class: '%oro_order.entity.order.class%' }
