services:
    oro_order.api.frontend.order_address_query_modifier:
        class: Oro\Bundle\OrderBundle\Api\OrderAddressQueryModifier
        arguments:
            - '@oro_entity.orm.entity_class_resolver'
        tags:
            - { name: oro.api.query_modifier, requestType: frontend }

    oro_order.api.update_price_by_value_and_currency:
        class: Oro\Bundle\CurrencyBundle\Api\Processor\UpdatePriceByValueAndCurrency
        tags:
            - { name: oro.api.processor, action: customize_form_data, event: pre_submit|post_validate, class: Oro\Bundle\OrderBundle\Entity\OrderLineItem }

    oro_order.api.update_order_line_item_product:
        class: Oro\Bundle\OrderBundle\Api\Processor\UpdateOrderLineItemProduct
        arguments:
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: customize_form_data, event: pre_validate, class: Oro\Bundle\OrderBundle\Entity\OrderLineItem }

    oro_order.api.add_discount_to_order:
        class: Oro\Bundle\OrderBundle\Api\Processor\AddDiscountToOrder
        arguments:
            - '@oro_order.order.total.total_helper'
        tags:
            - { name: oro.api.processor, action: customize_form_data, event: pre_validate, class: Oro\Bundle\OrderBundle\Entity\OrderDiscount }

    oro_order.api.compute_order_payment_status:
        class: Oro\Bundle\OrderBundle\Api\Processor\ComputeOrderPaymentStatus
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_payment.formatter.payment_status_label'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, collection: true, requestType: frontend, class: Oro\Bundle\OrderBundle\Entity\Order }

    oro_order.api.compute_order_payment_method:
        class: Oro\Bundle\OrderBundle\Api\Processor\ComputeOrderPaymentMethod
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_payment.formatter.payment_method_label'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, collection: true, requestType: frontend, class: Oro\Bundle\OrderBundle\Entity\Order }

    oro_order.api.compute_order_shipping:
        class: Oro\Bundle\OrderBundle\Api\Processor\ComputeOrderShipping
        arguments:
            - '@?oro_shipping.translator.shipping_method_label'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, class: Oro\Bundle\OrderBundle\Entity\Order }

    oro_order.api.set_order_default_discount_type:
        class: Oro\Bundle\OrderBundle\Api\Processor\SetOrderDefaultDiscountType
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, class: Oro\Bundle\OrderBundle\Entity\Order }
