operations:
    b2b_flow_checkout_single_page_new_address:
        label: oro.checkout.form.address.manual
        enabled: true
        applications: [commerce]
        acl_resource: oro_checkout_frontend_checkout
        frontend_options:
            template: OroCheckoutBundle:Action:address.html.twig

    b2b_flow_checkout_single_page_new_billing_address:
        extends: b2b_flow_checkout_single_page_new_address
        attributes:
            visitor_email:
                label: oro.customer.customeruser.username.label
                type: string
            address:
                property_path: data.billingAddress
            save_address:
                label: oro.checkout.save_billing_address.label
                type: boolean
        form_options:
            attribute_fields:
                visitor_email:
                    form_type: oro_customer_visitor_email_address
                    options:
                        required: true
                address:
                    form_type: oro_checkout_address
                    options:
                        object: $.data
                        addressType: 'billing'
                        isEditEnabled: true
                        required: true
                        constraints:
                            - Valid: ~
                            - NotBlank: ~
                            - Oro\Bundle\AddressBundle\Validator\Constraints\NameOrOrganization: ~
                save_address:
                    form_type: oro_save_address
        form_init:
            - '@tree':
                conditions:
                    '@and':
                        - '@not_blank': $.data.customerUser
                        - '@not_blank': $.data.customerUser.firstName
                        - '@not_blank': $.data.billingAddress
                actions:
                    - '@assign_value': [$.visitor_email, $.data.customerUser.email]
            - '@assign_value': [$.address, $.data.billingAddress]
            - '@assign_value': [$.address.customerAddress, null]
            - '@assign_value': [$.address.customerUserAddress, null]
            - '@tree':
                conditions:
                    '@and':
                        - '@acl_granted': 'CREATE;entity:OroCustomerBundle:CustomerUserAddress'
                        - '@acl_granted': 'CREATE;entity:OroCustomerBundle:CustomerAddress'
                actions:
                    - '@assign_value': [$.save_address, $.data.saveBillingAddress]
        actions:
            - '@tree':
                conditions:
                    '@and':
                        - '@not_blank': $.visitor_email
                        - '@not_blank': $.data.customerUser
                actions:
                    - '@assign_value': [$.data.customerUser.firstName, null]
                    - '@run_action_group':
                        action_group: b2b_flow_checkout_update_guest_customer_user
                        parameters_mapping:
                            checkout: $.data
                            visitor_email: $.visitor_email
                            billing_address: $.data.billingAddress
            - '@assign_value': [$.data.saveBillingAddress, $.save_address]
            - '@run_action_group':
                action_group: b2b_flow_checkout_update_shipping_address
                parameters_mapping:
                    checkout: $.data
                    billing_address_has_shipping: $.data.shipToBillingAddress
            - '@run_action_group':
                action_group: b2b_flow_checkout_update_shipping_method
                parameters_mapping:
                    checkout: $.data
            - '@tree':
                conditions:
                    '@empty': $.data.shippingCost
                actions:
                    - '@unset_value': $.data.shippingMethod
                    - '@call_service_method':
                         service: oro_checkout.action.default_shipping_method_setter
                         method: setDefaultShippingMethod
                         method_parameters: [$.data]
            - '@flush_entity': [$.address]
            - '@flush_entity': [$.data]

    b2b_flow_checkout_single_page_new_shipping_address:
        extends: b2b_flow_checkout_single_page_new_address
        attributes:
            address:
                property_path: data.shippingAddress
            save_address:
                label: oro.checkout.save_shipping_address.label
                type: boolean
        form_options:
            attribute_fields:
                address:
                    form_type: oro_checkout_address
                    options:
                        object: $.data
                        addressType: 'shipping'
                        isEditEnabled: true
                        required: true
                        constraints:
                            - Valid: ~
                            - NotBlank: ~
                            - Oro\Bundle\AddressBundle\Validator\Constraints\NameOrOrganization: ~
                save_address:
                    form_type: oro_save_address
        form_init:
            - '@assign_value': [$.address, $.data.shippingAddress]
            - '@assign_value': [$.address.customerAddress, null]
            - '@assign_value': [$.address.customerUserAddress, null]
            - '@tree':
                conditions:
                    '@and':
                        - '@acl_granted': 'CREATE;entity:OroCustomerBundle:CustomerUserAddress'
                        - '@acl_granted': 'CREATE;entity:OroCustomerBundle:CustomerAddress'
                actions:
                    - '@assign_value': [$.save_address, $.data.saveShippingAddress]
        actions:
            - '@assign_value': [$.data.saveShippingAddress, $.save_address]
            - '@run_action_group':
                action_group: b2b_flow_checkout_update_shipping_method
                parameters_mapping:
                    checkout: $.data
            - '@tree':
                conditions:
                    '@empty': $.data.shippingCost
                actions:
                    - '@unset_value': $.data.shippingMethod
                    - '@call_service_method':
                         service: oro_checkout.action.default_shipping_method_setter
                         method: setDefaultShippingMethod
                         method_parameters: [$.data]
            - '@flush_entity': [$.address]
            - '@flush_entity': [$.data]
