layout:
    imports:
        - oro_allproducts_grid

    actions:
        - '@setBlockTheme':
            themes: 'product_index.html.twig'

        - '@setOption':
            id: product_datagrid
            optionName: grid_name
            optionValue: frontend-catalog-allproducts-grid

        - '@addTree':
            items:
                category_title:
                    blockType: text
                    options:
                        text: 'oro.catalog.all_products.label'
            tree:
                page_main_header:
                    category_title: ~
        - '@remove':
            id: product_datagrid_cell_categoryId
        - '@remove':
            id: product_datagrid_cell_categoryTitle
        - '@remove':
            id: product_datagrid_toolbar_pagination
        - '@remove':
             id: product_datagrid_toolbar_page_size
        - '@remove':
             id: product_datagrid_toolbar_sorting
