workflows:
    b2b_flow_checkout:
        steps:
            customer_consents:
                order: 0
                allowed_transitions:
                    - continue_to_billing_address
                    - continue_checkout_as_guest
                    - continue_checkout_as_registered_user
                    - start_checkout_as_guest_system
                    - start_from_quickorderform
            enter_credentials_step:
                allowed_transitions:
                    - back_to_customer_consents
                    - continue_checkout_as_guest
                    - continue_checkout_as_registered_user
                    - start_checkout_as_guest_system
            enter_billing_address:
                allowed_transitions:
                    - back_to_customer_consents
                    - continue_to_shipping_address
                    - start_checkout_as_guest_system
                    - continue_checkout_as_guest
                    - continue_checkout_as_registered_user
