workflows:
    b2b_flow_checkout:
        transitions:
            continue_to_billing_address:
                step_to: enter_billing_address
                transition_definition: continue_to_billing_address_definition
                display_type: page
                frontend_options:
                    is_checkout_continue: true
                    is_checkout_show_errors: true
                form_type: Oro\Bundle\ConsentBundle\Form\Type\CustomerConsentTransitionType
                form_options:
                    form_init:
                        - '@generate_checkout_state_snapshot':
                            entity: $checkout
                            attribute: $.result.initCheckoutState
                    attribute_fields:
                        customerConsents:
                            form_type: Oro\Bundle\ConsentBundle\Form\Type\CheckoutCustomerConsentsType
                            options:
                                checkout: $checkout
                                constraints:
                                    - Oro\Bundle\ConsentBundle\Validator\Constraints\RequiredConsents: ~
                        state_token:
                            form_type: Symfony\Component\Form\Extension\Core\Type\HiddenType
                            options:
                                data: $internal_state_token

            back_to_customer_consents:
                step_to: customer_consents
                transition_definition: back_to_customer_consents_definition
                is_unavailable_hidden: true
                frontend_options:
                    is_checkout_back: true

            # Rewritten option on declared transitions
            start_from_shoppinglist:
                step_to: customer_consents

            start_from_quickorderform:
                step_to: customer_consents

            continue_checkout_as_registered_user:
                step_to: customer_consents
                transition_definition: continue_to_customer_consents_definition

            continue_checkout_as_guest:
                step_to: customer_consents
                transition_definition: continue_to_customer_consents_definition
