workflows:
    b2b_flow_checkout:
        transition_definitions:
            continue_to_customer_consents_definition:
                actions:
                    - '@generate_checkout_state_snapshot':
                        entity: $checkout
                        attribute: $.result.actualCheckoutState
                    - '@save_checkout_state':
                        entity: $checkout
                        state: $.result.actualCheckoutState
                        attribute: $state_token
                    - '@assign_value': [$internal_state_token, $state_token]

                    - '@tree':
                          conditions:
                              '@and':
                                  - '@current_step_name_is_equal':
                                      main_entity: $checkout
                                      step_name: 'customer_consents'
                                      workflow: $.definition.name
                                  - '@or':
                                      - '@not':
                                          - '@feature_enabled':
                                              feature: 'consents'
                                      - '@not':
                                          - '@checkout_has_unaccepted_consents':
                                              checkout: $checkout
                          actions:
                              - '@transit_workflow':
                                  parameters:
                                      entity: $checkout
                                      transition: continue_to_billing_address
                                      workflow: $.definition.name

            back_to_customer_consents_definition:
                preconditions:
                    '@and':
                        - '@feature_enabled':
                            feature: 'consents'
                        - '@equal': [$checkout.completed, false]
                actions:
                    - '@generate_checkout_state_snapshot':
                        entity: $checkout
                        attribute: $.result.actualCheckoutState
                    - '@save_checkout_state':
                        entity: $checkout
                        state: $.result.actualCheckoutState
                        attribute: $state_token
                    - '@assign_value': [$internal_state_token, $state_token]

            continue_to_billing_address_definition:
                preactions:
                    - '@generate_checkout_state_snapshot':
                        entity: $checkout
                        attribute: $.result.currentCheckoutState
                    - '@get_checkout_state':
                        entity: $checkout
                        token: $state_token
                        attribute: $.result.tokenCheckoutState

            # Additional options for declared transition definitions
            start_from_quickorderform_definition:
                actions:
                    - '@tree':
                        conditions:
                            '@and':
                                - '@current_step_name_is_equal':
                                    main_entity: $checkout
                                    step_name: 'customer_consents'
                                    workflow: $.definition.name
                                - '@or':
                                    - '@not':
                                        - '@feature_enabled':
                                            feature: 'consents'
                                    - '@not':
                                        - '@checkout_has_unaccepted_consents':
                                            checkout: $checkout
                        actions:
                            - '@transit_workflow':
                                parameters:
                                    entity: $checkout
                                    transition: continue_to_billing_address
                                    workflow: $.definition.name

            start_from_shoppinglist_definition:
                actions:
                    - '@tree':
                          conditions:
                              '@and':
                                  - '@current_step_name_is_equal':
                                      main_entity: $checkout
                                      step_name: 'customer_consents'
                                      workflow: $.definition.name
                                  - '@or':
                                      - '@not':
                                          - '@feature_enabled':
                                              feature: 'consents'
                                      - '@not':
                                          - '@checkout_has_unaccepted_consents':
                                              checkout: $checkout
                          actions:
                              - '@transit_workflow':
                                  parameters:
                                      entity: $checkout
                                      transition: continue_to_billing_address
                                      workflow: $.definition.name
