services:
    oro_product.importexport.normalizer.product_image.test:
        alias: oro_product.importexport.normalizer.product_image

    oro_product.tests.migration_listener:
        class: Oro\Bundle\ProductBundle\Tests\Functional\Environment\TestEntitiesMigrationListener
        tags:
            - { name: kernel.event_listener, event: oro_migration.post_up, method: onPostUp }
