parameters:
    oro_product.entity.related_product.class: Oro\Bundle\ProductBundle\Entity\RelatedItem\RelatedProduct
    oro_product.product_unit.translations_mapping:
        messages:
            'oro.product_unit.{unit}.label.full': '{full}'
            'oro.product_unit.{unit}.label.full_plural': '{full_plural}'
            'oro.product_unit.{unit}.label.short': '{short}'
            'oro.product_unit.{unit}.label.short_plural': '{short_plural}'
            'oro.product_unit.{unit}.value.full': '{0} none|{1} %%count%% {full}|]1,Inf] %%count%% {full_plural}'
            'oro.product_unit.{unit}.value.full_fraction': '%%count%% {full}'
            'oro.product_unit.{unit}.value.full_fraction_gt_1': '%%count%% {full_plural}'
            'oro.product_unit.{unit}.value.short': '{0} none|{1} %%count%% {short}|]1,Inf] %%count%% {short_plural}'
            'oro.product_unit.{unit}.value.short_fraction': '%%count%% {short}'
            'oro.product_unit.{unit}.value.short_fraction_gt_1': '%%count%% {short_plural}'
        jsmessages:
            'oro.product.product_unit.{unit}.label.full': '{full}'
            'oro.product.product_unit.{unit}.label.full_plural': '{full_plural}'
            'oro.product.product_unit.{unit}.label.short': '{short}'
            'oro.product.product_unit.{unit}.label.short_plural': '{short_plural}'
            'oro.product.product_unit.{unit}.value.full': '{0} none|]0,1] {{ count }} {full}|]1,Inf]{{ count }} {full_plural}'
            'oro.product.product_unit.{unit}.value.short': '{0} none|]0,1] {{ count }} {short}|]1,Inf]{{ count }} {short_plural}'
            'oro.product.product_unit.{unit}.value.label': '{0} none|]0,1] {short}|]1,Inf] {short_plural}'

services:
    oro_product.api.compute_product_unit_label:
        class: Oro\Bundle\ProductBundle\Api\Processor\ComputeProductUnitLabel
        arguments:
            - '@oro_product.formatter.product_unit_label'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\ProductBundle\Entity\ProductUnit }

    oro_product.api.validate_product_unit_label_fields:
        class: Oro\Bundle\ProductBundle\Api\Processor\ValidateProductUnitLabelFields
        tags:
            - { name: oro.api.processor, action: customize_form_data, event: post_submit, class: Oro\Bundle\ProductBundle\Entity\ProductUnit }

    oro_product.api.save_product_unit_labels:
        class: Oro\Bundle\ProductBundle\Api\Processor\SaveProductUnitLabels
        arguments:
            - '@oro_translation.manager.translation'
            - '@translator.default'
            - '@oro_product.formatter.product_unit_label'
            - '@oro_message_queue.client.message_producer'
            - '%oro_product.product_unit.translations_mapping%'
        tags:
            - { name: oro.api.processor, action: customize_form_data, event: post_submit, class: Oro\Bundle\ProductBundle\Entity\ProductUnit, priority: -100 }

    oro_product.api.add_validate_unit_precisions_duplicate_form_listener:
        class: Oro\Bundle\ProductBundle\Api\Processor\AddValidateUnitPrecisionsDuplicateFormListener
        tags:
            - { name: oro.api.processor, action: create, group: transform_data, class: Oro\Bundle\ProductBundle\Entity\Product, priority: 90 }
            - { name: oro.api.processor, action: update, group: transform_data, class: Oro\Bundle\ProductBundle\Entity\Product, priority: 90 }

    oro_product.api.create.add_product_type_data_transformers:
        class: Oro\Bundle\ProductBundle\Api\Processor\Create\AddProductTypeDataTransformers
        tags:
            - { name: oro.api.processor, action: create, group: transform_data, class: Oro\Bundle\ProductBundle\Entity\Product, priority: 95 }

    oro_product.api.create.related_product.security_check:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemSecurityCheck
        arguments:
            - '@oro_api.security.authorization_checker'
            - ['VIEW', 'EDIT']
        tags:
            - { name: oro.api.processor, action: create, group: security_check, class: '%oro_product.entity.related_product.class%', priority: 100}

    oro_product.api.delete.related_product.security_check:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemSecurityCheck
        arguments:
            - '@oro_api.security.authorization_checker'
            - ['EDIT']
        tags:
            - { name: oro.api.processor, action: delete, group: security_check, class: '%oro_product.entity.related_product.class%', priority: 100}
            - { name: oro.api.processor, action: delete_list, group: security_check, class: '%oro_product.entity.related_product.class%', priority: 100}

    oro_product.api.get.related_product.security_check:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemSecurityCheck
        arguments:
            - '@oro_api.security.authorization_checker'
            - ['VIEW']
        tags:
            - { name: oro.api.processor, action: get, group: security_check, class: '%oro_product.entity.related_product.class%', priority: 100}
            - { name: oro.api.processor, action: get_list, group: security_check, class: '%oro_product.entity.related_product.class%', priority: 100}

    oro_product.api.create.add_related_product:
        class: Oro\Bundle\ProductBundle\Api\Processor\Create\AddRelatedProduct
        arguments:
            - '@oro_product.related_item.related_product.assigner_database_strategy'
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, class: '%oro_product.entity.related_product.class%', priority: 100}

    oro_product.api.get.related_product.acl_query:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemAclCheck
        arguments: ['@oro_api.entity_serializer.doctrine_helper']
        tags:
            - { name: oro.api.processor, action: get, group: build_query, class: '%oro_product.entity.related_product.class%', priority: -200}
            - { name: oro.api.processor, action: get_list, group: build_query, class: '%oro_product.entity.related_product.class%', priority: -200}

    oro_product.api.delete.related_product.build_single_item_query:
        class: Oro\Bundle\ApiBundle\Processor\Shared\BuildSingleItemQuery
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_api.criteria_connector'
            - '@oro_api.entity_id_helper'
        tags:
            - { name: oro.api.processor, action: delete, group: load_data, class: '%oro_product.entity.related_product.class%', priority: 10 }

    oro_product.api.delete.related_product.load_entity_by_orm_query:
        class: Oro\Bundle\ApiBundle\Processor\Shared\LoadEntityByOrmQuery
        arguments:
            - '@oro_entity.query_hint_resolver'
        tags:
            - { name: oro.api.processor, action: delete, group: load_data, class: '%oro_product.entity.related_product.class%', priority: 0 }

    oro_product.api.delete.related_product.acl_query:
        class: Oro\Bundle\ProductBundle\Api\Processor\Delete\RelatedItemAclCheck
        arguments: ['@oro_api.entity_serializer.doctrine_helper']
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]
        tags:
            - { name: oro.api.processor, action: delete, group: load_data, class: '%oro_product.entity.related_product.class%', priority: 5}
            - { name: oro.api.processor, action: delete_list, group: build_query, class: '%oro_product.entity.related_product.class%', priority: -200}

    oro_product.api.add_image_path_to_file:
        class: Oro\Bundle\ProductBundle\Api\Processor\AddImagePathToFile
        arguments:
            - '@oro_attachment.manager'
            - '@oro_api.doctrine_helper'
            - '@oro_layout.provider.image_type'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\AttachmentBundle\Entity\File }
