services:
    oro_product.api.add_validate_unit_precisions_duplicate_form_listener:
        class: Oro\Bundle\ProductBundle\Api\Processor\AddValidateUnitPrecisionsDuplicateFormListener
        tags:
            - { name: oro.api.processor, action: create, group: transform_data, class: Oro\Bundle\ProductBundle\Entity\Product, priority: 90 }
            - { name: oro.api.processor, action: update, group: transform_data, class: Oro\Bundle\ProductBundle\Entity\Product, priority: 90 }

    oro_product.api.create.add_product_type_data_transformers:
        class: Oro\Bundle\ProductBundle\Api\Processor\Create\AddProductTypeDataTransformers
        tags:
            - { name: oro.api.processor, action: create, group: transform_data, class: Oro\Bundle\ProductBundle\Entity\Product, priority: 95 }

    oro_product.api.create.related_product.security_check:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemSecurityCheck
        arguments:
            - '@security.authorization_checker'
            - ['VIEW', 'EDIT']
            - ['oro_related_products_edit']
        tags:
            - { name: oro.api.processor, action: create, group: security_check, class: Oro\Bundle\ProductBundle\Entity\RelatedItem\RelatedProduct, priority: 100}

    oro_product.api.delete.related_product.security_check:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemSecurityCheck
        arguments:
            - '@security.authorization_checker'
            - ['EDIT']
            - ['oro_related_products_edit']
        tags:
            - { name: oro.api.processor, action: delete, group: security_check, class: Oro\Bundle\ProductBundle\Entity\RelatedItem\RelatedProduct, priority: 100}
            - { name: oro.api.processor, action: delete_list, group: security_check, class: Oro\Bundle\ProductBundle\Entity\RelatedItem\RelatedProduct, priority: 100}

    oro_product.api.get.related_product.security_check:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemSecurityCheck
        arguments:
            - '@security.authorization_checker'
            - ['VIEW']
            - ['oro_related_products_edit']
        tags:
            - { name: oro.api.processor, action: get, group: security_check, class: Oro\Bundle\ProductBundle\Entity\RelatedItem\RelatedProduct, priority: 100}
            - { name: oro.api.processor, action: get_list, group: security_check, class: Oro\Bundle\ProductBundle\Entity\RelatedItem\RelatedProduct, priority: 100}

    oro_product.api.create.add_related_product:
        class: Oro\Bundle\ProductBundle\Api\Processor\Create\AddRelatedProduct
        arguments:
            - '@oro_product.related_item.related_product.assigner_database_strategy'
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, class: Oro\Bundle\ProductBundle\Entity\RelatedItem\RelatedProduct, priority: 100}
