parameters:
    oro_product.entity.related_product.class: Oro\Bundle\ProductBundle\Entity\RelatedItem\RelatedProduct

services:
    oro_product.api.compute_product_unit_label:
        class: Oro\Bundle\ProductBundle\Api\Processor\ComputeProductUnitLabel
        arguments:
            - '@oro_product.formatter.product_unit_label'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, class: '%oro_product.entity.product_unit.class%' }

    oro_product.api.compute_product_image:
        class: Oro\Bundle\ProductBundle\Api\Processor\ComputeProductImageFields
        arguments:
            - '@oro_attachment.manager'
            - '@oro_layout.provider.image_type'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, collection: true, class: Oro\Bundle\ProductBundle\Entity\ProductImage }
            
    oro_product.api.compute_product_unit_prcisions:
        class: Oro\Bundle\ProductBundle\Api\Processor\ComputeProductUnitPrecisions
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, class: Oro\Bundle\ProductBundle\Entity\Product }

    oro_product.api.compute_product_urls:
        class: Oro\Bundle\RedirectBundle\Api\Processor\ComputeUrlFields
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_locale.helper.localization'
            - '@oro_config.manager'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, collection: true, class: Oro\Bundle\ProductBundle\Entity\Product }

    oro_product.api.frontend.product_status_query_modifier:
        class: Oro\Bundle\ProductBundle\Api\ProductStatusQueryModifier
        arguments:
            - '@oro_entity.orm.entity_class_resolver'
        tags:
            - { name: oro.api.query_modifier, requestType: frontend }

    oro_product.api.frontend.product_status_mandatory_field_provider:
        class: Oro\Bundle\ProductBundle\Api\ProductStatusMandatoryFieldProvider
        tags:
            - { name: oro.api.mandatory_field_provider, requestType: frontend }

    oro_product.api.set_variant_products_association_query:
        class: Oro\Bundle\ProductBundle\Api\Processor\SetVariantProductsAssociationQuery
        arguments:
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: get_config, extra: '!identifier_fields_only&definition', requestType: frontend, class: Oro\Bundle\ProductBundle\Entity\Product, priority: -35 }

    oro_product.api.build_variant_products_subresource_query:
        class: Oro\Bundle\ProductBundle\Api\Processor\BuildVariantProductsSubresourceQuery
        arguments:
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: get_subresource, group: build_query, requestType: frontend, class: Oro\Bundle\ProductBundle\Entity\Product, association: variantProducts, priority: -90 }
            - { name: oro.api.processor, action: get_relationship, group: build_query, requestType: frontend, class: Oro\Bundle\ProductBundle\Entity\Product, association: variantProducts, priority: -90 }

    oro_product.api.compute_product_attributes:
        class: Oro\Bundle\ProductBundle\Api\Processor\ComputeProductAttributes
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_entity_config.config_manager'
            - '@oro_entity_extend.extend.field_type_helper'
            - '@oro_product.api.product_attribute_value_loader'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, collection: true, requestType: frontend, class: Oro\Bundle\ProductBundle\Entity\Product, priority: -10 }

    oro_product.api.product_attribute_value_loader:
        class: Oro\Bundle\ProductBundle\Api\ProductAttributeValueLoader
        public: false
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_api.get_config.processor'
            - '@oro_api.entity_serializer'
            - '@oro_api.metadata_provider'
            - '@oro_api.entity_id_transformer_registry'

    oro_product.api.update_product_family_query:
        class: Oro\Bundle\ProductBundle\Api\Processor\UpdateProductFamilyQuery
        tags:
            - { name: oro.api.processor, action: get, group: build_query, requestType: frontend, class: Oro\Bundle\EntityConfigBundle\Attribute\Entity\AttributeFamily, priority: -150 }
            - { name: oro.api.processor, action: get_list, group: build_query, requestType: frontend, class: Oro\Bundle\EntityConfigBundle\Attribute\Entity\AttributeFamily, priority: -150 }

    oro_product.api.update_product_image_query:
        class: Oro\Bundle\ProductBundle\Api\Processor\UpdateProductImageQuery
        arguments:
            - '@oro_api.entity_serializer.query_modifier_registry'
        tags:
            - { name: oro.api.processor, action: get, group: build_query, requestType: frontend, class: Oro\Bundle\ProductBundle\Entity\ProductImage, priority: -150 }
            - { name: oro.api.processor, action: get_list, group: build_query, requestType: frontend, class: Oro\Bundle\ProductBundle\Entity\ProductImage, priority: -150 }

    oro_product.api.add_validate_unit_precisions_duplicate_form_listener:
        class: Oro\Bundle\ProductBundle\Api\Processor\AddValidateUnitPrecisionsDuplicateFormListener
        tags:
            - { name: oro.api.processor, action: create, group: transform_data, class: Oro\Bundle\ProductBundle\Entity\Product, priority: 90 }
            - { name: oro.api.processor, action: update, group: transform_data, class: Oro\Bundle\ProductBundle\Entity\Product, priority: 90 }

    oro_product.api.create.add_product_type_data_transformers:
        class: Oro\Bundle\ProductBundle\Api\Processor\Create\AddProductTypeDataTransformers
        tags:
            - { name: oro.api.processor, action: create, group: transform_data, class: Oro\Bundle\ProductBundle\Entity\Product, priority: 95 }

    oro_product.api.create.related_product.security_check:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemSecurityCheck
        arguments:
            - '@oro_api.security.authorization_checker'
            - ['VIEW', 'EDIT']
        tags:
            - { name: oro.api.processor, action: create, group: security_check, class: '%oro_product.entity.related_product.class%', priority: 100}

    oro_product.api.delete.related_product.security_check:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemSecurityCheck
        arguments:
            - '@oro_api.security.authorization_checker'
            - ['EDIT']
        tags:
            - { name: oro.api.processor, action: delete, group: security_check, class: '%oro_product.entity.related_product.class%', priority: 100}
            - { name: oro.api.processor, action: delete_list, group: security_check, class: '%oro_product.entity.related_product.class%', priority: 100}

    oro_product.api.get.related_product.security_check:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemSecurityCheck
        arguments:
            - '@oro_api.security.authorization_checker'
            - ['VIEW']
        tags:
            - { name: oro.api.processor, action: get, group: security_check, class: '%oro_product.entity.related_product.class%', priority: 100}
            - { name: oro.api.processor, action: get_list, group: security_check, class: '%oro_product.entity.related_product.class%', priority: 100}

    oro_product.api.create.add_related_product:
        class: Oro\Bundle\ProductBundle\Api\Processor\Create\AddRelatedProduct
        arguments:
            - '@oro_product.related_item.related_product.assigner_database_strategy'
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, class: '%oro_product.entity.related_product.class%', priority: 100}

    oro_product.api.get.related_product.acl_query:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemAclCheck
        arguments: ['@oro_api.entity_serializer.doctrine_helper']
        tags:
            - { name: oro.api.processor, action: get, group: build_query, class: '%oro_product.entity.related_product.class%', priority: -200}
            - { name: oro.api.processor, action: get_list, group: build_query, class: '%oro_product.entity.related_product.class%', priority: -200}

    oro_product.api.delete.related_product.build_single_item_query:
        class: Oro\Bundle\ApiBundle\Processor\Shared\BuildSingleItemQuery
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_api.entity_id_helper'
        tags:
            - { name: oro.api.processor, action: delete, group: load_data, class: '%oro_product.entity.related_product.class%', priority: 10 }

    oro_product.api.delete.related_product.load_entity_by_orm_query:
        class: Oro\Bundle\ApiBundle\Processor\Shared\LoadEntityByOrmQuery
        arguments:
            - '@oro_entity.query_hint_resolver'
        tags:
            - { name: oro.api.processor, action: delete, group: load_data, class: '%oro_product.entity.related_product.class%', priority: 0 }

    oro_product.api.delete.related_product.acl_query:
        class: Oro\Bundle\ProductBundle\Api\Processor\Delete\RelatedItemAclCheck
        arguments: ['@oro_api.entity_serializer.doctrine_helper']
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]
        tags:
            - { name: oro.api.processor, action: delete, group: load_data, class: '%oro_product.entity.related_product.class%', priority: 5}
            - { name: oro.api.processor, action: delete_list, group: build_query, class: '%oro_product.entity.related_product.class%', priority: -200}

    oro_product.api.add_image_path_to_file:
        class: Oro\Bundle\ProductBundle\Api\Processor\AddImagePathToFile
        arguments:
            - '@oro_attachment.manager'
            - '@oro_api.doctrine_helper'
            - '@oro_layout.provider.image_type'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\AttachmentBundle\Entity\File }
