oro_web_catalog:
    resource:     "@OroWebCatalogBundle/Controller/WebCatalogController.php"
    type:         annotation
    prefix:       /webcatalog

oro_web_catalog_content_node:
    resource:     "@OroWebCatalogBundle/Controller/ContentNodeController.php"
    type:         annotation
    prefix:       /webcatalog/node

oro_web_catalog_bundle_api:
    resource:     "@OroWebCatalogBundle/Resources/config/oro/routing_api.yml"
    requirements:
        version:  latest|v1
        _format:  json
    defaults:
        version:  latest
