services:
    Oro\Bundle\ShoppingListBundle\Command\ClearExpiredShoppingListsCommand:
        public: false
        class: Oro\Bundle\ShoppingListBundle\Command\ClearExpiredShoppingListsCommand
        tags:
            - { name: console.command }

    Oro\Bundle\ShoppingListBundle\Command\ClearExpiredCustomerVisitorsCommand:
        public: false
        class: Oro\Bundle\ShoppingListBundle\Command\ClearExpiredCustomerVisitorsCommand
        tags:
            - { name: console.command }
