assets:
    css:
        'orocatalog':
            - 'bundles/orocatalog/css/less/categories.less'
            - 'bundles/orocatalog/css/less/product-grid-sidebar.less'
            - 'bundles/orocatalog/css/less/categories-sidebar.less'
