assetic:
    assets:
        tinymce_fullscreen:
            inputs:
                - '%kernel.project_dir%/vendor/tinymce/tinymce/plugins/fullscreen/plugin.min.js'
            output: bundles/tinymce/plugins/fullscreen/plugin.min.js
