Oro\Bundle\ProductBundle\Entity\Product:
    alias: oro_product_WEBSITE_ID
    fields:
        -
            name: product_id
            type: integer
        -
            name: name_LOCALIZATION_ID
            type: text
        -
            name: sku
            type: text
        -
            name: sku_uppercase
            type: text
        -
            name: new_arrival
            type: integer
        -
            name: short_description_LOCALIZATION_ID
            type: text
        -
            name: status
            type: text
        -
            name: type
            type: text
        -
            name: inventory_status
            type: text
        -
            name:  all_text
            type:  text
            store: false
            default_search_field: true
        -
            name:  all_text_LOCALIZATION_ID
            type:  text
            store: false
        -
            name: assigned_to_ASSIGN_TYPE_ASSIGN_ID
            type: integer
        -
            name: image_product_large
            type: text
        -
            name: image_product_medium
            type: text
        -
            name: product_units
            type: text

Oro\Bundle\ProductBundle\Entity\Brand:
    alias: oro_brand_WEBSITE_ID
    fields:
        -
            name: name_LOCALIZATION_ID
            type: text
        -
            name: short_description_LOCALIZATION_ID
            type: text
