layout:
    actions:
        - '@setBlockTheme':
            themes: 'OroCatalogBundle:layouts:blank/oro_product_frontend_product_index/product_index.html.twig'
        - '@addTree':
            items:
                breadcrumbs:
                    blockType: breadcrumbs
                    options:
                        breadcrumbs: '=data["category_breadcrumbs"].getItems()'
                breadcrumbs_filters:
                    blockType: block
                    options:
                        visible: false
                category_picture:
                    blockType: category
                    options:
                        category: '=data["category"].getCurrentCategory()'
                        attr:
                            src: '=data["category_image_placeholder"].getPath("product_original")'
                category_title:
                    blockType: text
                    options:
                        text: '=data["locale"].getLocalizedValue(data["category"].getCurrentCategory().getTitles())'
            tree:
                page_main_header:
                    category_picture: ~
                    breadcrumbs:
                        breadcrumbs_filters: ~
                    category_title: ~
