imports:
    - { resource: 'actions/b2b_flow_checkout.yml' }

operations:
    UPDATE:
        exclude_datagrids:
            - frontend-checkouts-grid

    oro_checkout_delete_order:
        extends: DELETE
        applications: [commerce]
        for_all_datagrids: false
        for_all_entities: false
        label: oro.checkout.grid.delete.label
        preconditions:
            '@and':
                - '@not_blank': $.data
                - '@equal': [$.data.completed, false]
        datagrids:
            - frontend-checkouts-grid
        replace:
            - applications
            - preconditions
            - datagrids
        preactions:
            - '@trans':
                id: oro.checkout.open_order.label
                attribute: $.entityLabel

    oro_checkout_frontend_view_order:
        label: oro.checkout.frontend.order.view.label
        applications: [commerce]
        datagrids:
            - frontend-checkouts-grid
        order: 20
        button_options:
            icon: fa-eye
        preactions:
            - '@tree':
                conditions:
                    '@equal': [$.data.completed, true]
                actions:
                    - '@call_method':
                        object: $.data.completedData
                        method: getOrderData
                        attribute: $.orderData
                    - '@tree':
                        conditions:
                            '@not_empty': $.orderData
                        actions:
                            - '@call_service_method':
                                service: oro_entity.entity_alias_resolver
                                method: getClassByAlias
                                method_parameters: [$.orderData.entityAlias]
                                attribute: $.entityClass
                            - '@find_entity':
                                class: $.entityClass
                                where: $.orderData.entityId
                                attribute: $.order
        preconditions:
            '@and':
                - '@equal': [$.data.completed, true]
                - '@not_empty': $.order
                - '@acl_granted': [VIEW, $.order]
        actions:
            - '@redirect':
                 route: 'oro_order_frontend_view'
                 route_parameters: {id: $.order.id}

    oro_checkout_frontend_quote_submit_to_order:
        label: oro.checkout.frontend.quote.submit_to_order
        applications: [commerce]
        routes:
            - oro_sale_quote_frontend_view
        order: 20
        acl_resource: [CHECKOUT_CREATE, $.data]
        button_options:
            icon: fa-pencil-square-o
            class:  quota-accept-btn
        preconditions:
            '@and':
                - '@quote_acceptable': $.data
                - '@workflow_available_by_record_group':
                    group_name: b2b_checkout_flow
                    entity_class: Oro\Bundle\CheckoutBundle\Entity\Checkout
        actions:
            - '@get_active_user': $.currentUser
            - '@find_entity':
                class: Oro\Bundle\SaleBundle\Entity\QuoteDemand
                attribute: $.quoteDemand
                where:
                    quote: $.data
                    customerUser: $.currentUser
            - '@tree':
                conditions:
                    '@empty': $.quoteDemand
                actions:
                    - '@create_entity':
                        parameters:
                            attribute: $.quoteDemand
                            class: Oro\Bundle\SaleBundle\Entity\QuoteDemand
                            data:
                                quote: $.data
                                customerUser: $.currentUser
                    - '@call_service_method':
                        service: oro_sale.manager.quote_demand_manager
                        method: recalculateSubtotals
                        method_parameters: [$.quoteDemand]
                    - '@flush_entity': $.quoteDemand
            - '@redirect':
                 route: 'oro_sale_quote_frontend_choice'
                 route_parameters: {id: $.quoteDemand.id}

action_groups:
    oro_update_shipping_price:
        parameters:
          checkout:
                type: Oro\Bundle\CheckoutBundle\Entity\Checkout
        actions:
            - '@call_service_method':
                service: oro_checkout.shipping_method.provider_main
                method: getPrice
                method_parameters: [$.checkout]
                attribute: $.checkout.shippingCost

    start_shoppinglist_checkout:
        parameters:
            shoppingList:
                type: Oro\Bundle\ShoppingListBundle\Entity\ShoppingList
            forceStartCheckout:
                type: bool
                default: false
            showErrors:
                type: bool
                default: false
            validateOnStartCheckout:
                type: bool
                default: true
        actions:
            - '@assign_url':
                attribute: $.editLink
                route: oro_shopping_list_frontend_view
                route_parameters: {id: $.shoppingList.id}
            - '@translate':
                id: 'oro.frontend.shoppinglist.workflow.remove_source.label'
                attribute: $.sourceRemoveLabel
            - '@run_action_group':
                action_group: start_checkout
                parameters_mapping:
                    sourceCriteria:
                        shoppingList: $.shoppingList
                    settings:
                        allow_manual_source_remove: true
                        remove_source: true
                        edit_order_link: $.editLink
                        source_remove_label: $.sourceRemoveLabel
                    force: $.forceStartCheckout
                    showErrors: $.showErrors
                    validateOnStartCheckout: $.validateOnStartCheckout
                results:
                    redirectUrl: $.redirectUrl
                    checkout: $.checkout
                    errors: $.errors

    start_checkout:
        parameters:
            sourceCriteria:
                type: array
            force:
                type: bool
                default: false
            data:
                type: array
                default: []
            settings:
                type: array
                default: []
            showErrors:
                type: bool
                default: false
        actions:
            - '@run_action_group':
                action_group: find_checkout
                parameters_mapping:
                    sourceCriteria: $.sourceCriteria
                    checkoutData: $.data
                    updateData: $.force
                results:
                    checkout: $.checkout
                    force: $.updateData

            - '@tree':
                conditions:
                    '@equal': [true, $.force]
                actions:
                    - '@run_action_group':
                        action_group: update_workflow_item
                        parameters_mapping:
                            entity: $.checkout
                            data: $.settings
            - '@redirect':
                conditions:
                    '@extendable':
                        events: [extendable_condition.start_checkout]
                        showErrors: $.showErrors
                parameters:
                    route: oro_checkout_frontend_checkout
                    route_parameters:
                        id: $.checkout.id

    find_checkout:
        parameters:
            sourceCriteria:
                type: array
            checkoutData:
                type: array
                default: []
            updateData:
                type: bool
                default: false
        actions:
            # find or create checkout and checkout source
            - '@get_available_workflow_by_record_group':
                attribute: $.currentWorkflow
                entity_class: 'Oro\Bundle\CheckoutBundle\Entity\Checkout'
                group_name: 'b2b_checkout_flow'

            - '@get_active_user_or_null': $.currentUser

            - '@tree':
                conditions:
                    '@not_empty': $.currentUser
                actions:
                    - '@call_service_method':
                        attribute: $.checkout
                        service: 'oro_checkout.repository.checkout'
                        method: findCheckoutByCustomerUserAndSourceCriteria
                        method_parameters:
                            - $.currentUser
                            - $.sourceCriteria
                            - $.currentWorkflow.name

            - '@call_service_method':
                attribute: $.currentWebsite
                service: oro_website.manager
                method: getCurrentWebsite

            - '@tree':
                conditions:
                    '@empty': $.checkout.id
                actions:
                    - '@create_entity':
                        attribute: $.source
                        class: 'Oro\Bundle\CheckoutBundle\Entity\CheckoutSource'
                        data: $.sourceCriteria
                    - '@create_entity':
                        attribute: $.checkout
                        class: 'Oro\Bundle\CheckoutBundle\Entity\Checkout'
                        data:
                            source: $.source
                            customerUser: $.currentUser
                            website: $.currentWebsite
                    - '@create_datetime': {attribute: $.checkout.createdAt}
                    - '@create_datetime': {attribute: $.checkout.updatedAt}
                    - '@assign_value': [$.updateData, true]

                    - '@start_workflow':
                        attribute: $.workflowItem
                        name: $.currentWorkflow.name
                        entity: $.checkout

            # update checkout data
            - '@tree':
                conditions:
                    '@and':
                        - '@not_empty': $.currentUser
                        - '@equal': [true, $.updateData]
                actions:
                    - '@assign_value': [$.checkout.customer, $.currentUser.customer]
                    - '@assign_value': [$.checkout.organization, $.currentUser.customer.organization]
                    - '@assign_value': [$.checkout.website, $.currentWebsite]
                    # update custom data
                    - '@copy_values': [$.checkout, $.checkoutData]

            # actualize user currency
            - '@call_service_method':
                attribute: $.checkout.currency
                service: oro_pricing.user_currency_manager
                method: getUserCurrency

            - '@flush_entity': $.checkout

    update_workflow_item:
        parameters:
            entity:
                type: object
            data:
                type: array
        actions:
            - '@get_available_workflow_by_record_group':
                attribute: $.currentWorkflow
                entity_class: 'Oro\Bundle\CheckoutBundle\Entity\Checkout'
                group_name: 'b2b_checkout_flow'

            - '@call_service_method':
                attribute: $.workflowItem
                service: oro_workflow.manager
                method: getWorkflowItem
                method_parameters: [$.entity, $.currentWorkflow.name]

            - '@copy_values': [$.workflowItem.data, $.data]

            - '@call_method':
                object: $.workflowItem
                method: setUpdated

            - '@flush_entity': $.workflowItem
