security:
    firewalls:
        guest_checkout:
            pattern:                 ^/customer/checkout|^/api/rest/latest/workflow/start/b2b_flow_checkout|^/api/latest/country/regions
            context:                 customer_identity
            anonymous_customer_user: true
