features:
    checkout_customer_users_registration:
        label: oro.checkout.system_configuration.fields.registration_allowed.label
        description: oro.checkout.system_configuration.fields.registration_allowed.tooltip
        toggle: oro_customer.registration_allowed
        configuration:
            - checkout_customer_users_registration

    guest_checkout:
        label: oro.checkout.system_configuration.fields.guest_checkout.label
        description: oro.checkout.system_configuration.fields.guest_checkout.tooltip
        toggle: oro_checkout.guest_checkout
        routes:
            - 'oro_checkout_frontend_checkout'
        configuration:
            - guest_checkout_owner_section
        strategy: affirmative
