system_configuration:
    groups:
        orders_history:
            title: oro.order.system_configuration.groups.orders_history.title
            icon: fa-book
        orders_history_open_orders:
            title: oro.checkout.system_configuration.groups.open_orders.title
        checkout:
            title: oro.checkout.system_configuration.groups.checkout.title
            icon: fa-credit-card
            page_reload: true
        guest_checkout:
            title: oro.checkout.system_configuration.groups.guest_checkout.title
        guest_checkout_owner_section:
            title: oro.checkout.system_configuration.groups.guest_checkout_owner.title
        checkout_increase_performance:
            title: oro.checkout.system_configuration.groups.checkout_increase_performance.title

    fields:
        oro_checkout.frontend_open_orders_separate_page:
            data_type: boolean
            type: choice
            priority: 10
            options:
                label: oro.checkout.system_configuration.fields.frontend_open_orders_separate_page.title
                choices:
                     - No
                     - Yes
        oro_checkout.guest_checkout:
            data_type: boolean
            type: oro_config_checkbox
            priority: 10
            options:
                label: oro.checkout.system_configuration.fields.guest_checkout.title
                tooltip: oro.checkout.system_configuration.fields.guest_checkout.tooltip
        oro_checkout.default_guest_checkout_owner:
            ui_only: true
            data_type: string
            type: oro_user_select
            priority: 20
            options:
                label: oro.checkout.system_configuration.fields.default_guest_checkout_owner.title
                tooltip: oro.checkout.system_configuration.fields.default_guest_checkout_owner.tooltip
                required: true
                constraints:
                    - NotBlank: ~

        oro_checkout.single_page_checkout_increase_performance:
            data_type: boolean
            type: oro_config_checkbox
            priority: 100
            options:
                label: oro.checkout.system_configuration.fields.single_page_checkout_increase_performance.title
                tooltip: oro.checkout.system_configuration.fields.single_page_checkout_increase_performance.tooltip

    tree:
        system_configuration:
            commerce:
                children:
                    sales:
                        children:
                            checkout:
                                children:
                                    guest_checkout:
                                        children:
                                            - oro_checkout.guest_checkout
                                    guest_checkout_owner_section:
                                        children:
                                            - oro_checkout.default_guest_checkout_owner
                                    checkout_increase_performance:
                                        children:
                                            - oro_checkout.single_page_checkout_increase_performance
                            orders_history:
                                children:
                                    orders_history_open_orders:
                                        children:
                                            - oro_checkout.frontend_open_orders_separate_page
