layout:
    actions:
        - '@setBlockTheme':
            themes: 'default.html.twig'
        - '@appendOption':
            id: page_main
            optionName: attr.class
            optionValue: ' offset-none'
        - '@addTree':
            items:
                featured_categories:
                    blockType: embedded_list
                    siblingId: featured_menu_container
                    options:
                        label: 'oro.catalog.featured_categories.label'
                        item_key: 'category'
                        items: '=data["featured_categories"].getAll([2,3,4,6,7,8,9,10])'
                        items_data:
                            categoryProductsCount: '=data["categories_products"].getCountByCategories([2,3,4,6,7,8,9,10])'
                        item_extra_class: 'embedded-list__item--hide-same'
                featured_category:
                    blockType: container
                featured_category_image:
                    blockType: block
                featured_category_desc:
                    blockType: container
                featured_category_label:
                    blockType: block
                featured_category_products:
                    blockType: block
            tree:
                page_content:
                    featured_categories:
                        featured_category:
                            featured_category_image: ~
                            featured_category_desc:
                                featured_category_label: ~
                                featured_category_products: ~
