doctrine:
    dbal:
        types:
            wysiwyg: Oro\Bundle\CMSBundle\DBAL\Types\WYSIWYGType
            wysiwyg_style: Oro\Bundle\CMSBundle\DBAL\Types\WYSIWYGStyleType
            wysiwyg_properties: Oro\Bundle\CMSBundle\DBAL\Types\WYSIWYGPropertiesType

liip_imagine:
    filter_sets:
        login_page_logo:
            quality:          95
            filters:
                relative_resize: { heighten: 80 }
                strip:        ~
        login_page:
            quality:          95
            filters:
                thumbnail: { size: [80, 80], mode: outbound }
                strip:        ~
        login_page_background:
            quality:          95
            filters:
                strip:        ~
        digital_asset_grapesjs:
            quality: 100
