doctrine:
    dbal:
        types:
            wysiwyg: Oro\Bundle\CMSBundle\DBAL\Types\WYSIWYGType
            wysiwyg_style: Oro\Bundle\CMSBundle\DBAL\Types\WYSIWYGStyleType
            wysiwyg_properties: Oro\Bundle\CMSBundle\DBAL\Types\WYSIWYGPropertiesType

liip_imagine:
    filter_sets:
        login_page_logo:
            quality:          95
            filters:
                relative_resize: { heighten: 80 }
                strip:        ~
        login_page:
            quality:          95
            filters:
                thumbnail: { size: [80, 80], mode: outbound }
                strip:        ~
        login_page_background:
            quality:          95
            filters:
                strip:        ~

oro_form:
    html_purifier_modes:
        lax:
            extends: default
            html_purifier_iframe_domains:
                - 'youtube.com/embed/'
                - 'player.vimeo.com/video/'
            html_allowed_elements:
                iframe:
                    attributes:
                        - id
                        - allowfullscreen
                        - frameborder
                        - height
                        - marginheight
                        - marginwidth
                        - name
                        - scrolling
                        - src
                        - width
