datagrids:
    cms-page-select-grid:
        acl_resource: oro_cms_page_view
        options:
            entityHint: oro.cms.page.entity_plural_label
        source:
            type:         orm
            query:
                select:
                    - page.id
                from:
                    - { table: '%oro_cms.entity.page.class%', alias: page }
        columns:
            id:
                label: oro.cms.page.id.label
            title:
                label: oro.cms.page.titles.singular_label
        properties:
            id: ~
            title:
                type: localized_value
                data_name: titles
        sorters:
            columns:
                id:
                    data_name: page.id
                title:
                    data_name: title
            default:
                id: ASC
        filters:
            columns:
                id:
                    type:      number
                    data_name: page.id
                title:
                    type:      string
                    data_name: title

    cms-login-page-grid:
        acl_resource: oro_cms_loginpage_view
        options:
            entity_pagination: true
            entityHint: oro.cms.loginpage.entity_plural_label
        source:
            type:         orm
            query:
                select:
                    - loginPage.id
                from:
                    - { table: '%oro_cms.entity.loginpage.class%', alias: loginPage }
        columns:
            id:
              label: oro.cms.loginpage.id.label
        properties:
            id: ~
            view_link:
                type:   url
                route:  oro_cms_loginpage_view
                params: [ id ]
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye
                acl_resource:  oro_cms_loginpage_view
                rowAction:     true

    cms-page-grid:
        acl_resource: oro_cms_page_view
        options:
            entity_pagination: true
            entityHint: oro.cms.page.entity_plural_label
        source:
            type:         orm
            query:
                select:
                    - page.id
                from:
                    - { table: '%oro_cms.entity.page.class%', alias: page }
        columns:
            id:
              label: oro.cms.page.id.label
            title:
              label: oro.cms.page.titles.singular_label
        properties:
            id: ~
            title:
                type: localized_value
                data_name: titles
            view_link:
                type:   url
                route:  oro_cms_page_view
                params: [ id ]
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye
                acl_resource:  oro_cms_page_view
                rowAction:     true
        sorters:
            columns:
                id:
                    data_name: page.id
                title:
                    data_name: title
        filters:
            columns:
                id:
                    type: number
                    data_name: page.id
                title:
                    type: string
                    data_name: title

    cms-content-block-grid:
        acl_resource: oro_cms_content_block_view
        options:
            entityHint: oro.cms.contentblock.entity_plural_label
        source:
            type: orm
            query:
                select:
                    - contentBlock.id
                    - contentBlock.alias
                    - contentBlock.enabled
                    - contentBlock.createdAt
                    - contentBlock.updatedAt
                from:
                    - { table: '%oro_cms.entity.content_block.class%', alias: contentBlock }
        columns:
            alias:
                label: oro.cms.contentblock.alias.label
            title:
                label: oro.cms.contentblock.titles.singular_label
            enabled:
                label: oro.cms.contentblock.enabled.label
                frontend_type: select
                choices:
                   Disabled: 0
                   Enabled: 1
            createdAt:
                label: oro.cms.contentblock.createdat.label
                frontend_type: datetime
            updatedAt:
                label: oro.cms.contentblock.updatedat.label
                frontend_type: datetime
        sorters:
            columns:
                alias:
                    data_name: contentBlock.alias
                title:
                    data_name: title
                enabled:
                    data_name: contentBlock.enabled
                createdAt:
                    data_name: contentBlock.createdAt
                updatedAt:
                    data_name: contentBlock.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                alias:
                    type: string
                    data_name: contentBlock.alias
                title:
                    type: string
                    data_name: title
                enabled:
                    type: boolean
                    data_name: contentBlock.enabled
                    options:
                        field_options:
                            choices:
                                oro.cms.contentblock.filters.disabled: 2
                                oro.cms.contentblock.filters.enabled: 1
                createdAt:
                    type: datetime
                    data_name: contentBlock.createdAt
                updatedAt:
                    type: datetime
                    data_name: contentBlock.updatedAt
        properties:
            id: ~
            title:
                type: localized_value
                data_name: titles
            view_link:
                type: url
                route: oro_cms_content_block_view
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye
                acl_resource:  oro_cms_content_block_view
                rowAction:     true

    cms-content-widget-grid:
        source:
            type: orm
            query:
                select:
                    - contentWidget.id
                    - contentWidget.name
                    - contentWidget.description
                    - contentWidget.widgetType
                    - contentWidget.layout
                    - contentWidget.createdAt
                    - contentWidget.updatedAt
                from:
                    - { table: 'Oro\Bundle\CMSBundle\Entity\ContentWidget', alias: contentWidget }
        columns:
            name:
                label: oro.cms.contentwidget.name.label
            description:
                label: oro.cms.contentwidget.description.label
                type: twig
                frontend_type: html
                template: OroCMSBundle:ContentWidget:Datagrid/description.html.twig
            widgetType:
                label: oro.cms.contentwidget.widget_type.label
                frontend_type: select
                choices: '@oro_cms.provider.content_widget_type->getAvailableContentWidgetTypes()'
            layout:
                label: oro.cms.contentwidget.layout.label
                type: twig
                frontend_type: html
                template: OroCMSBundle:ContentWidget:Datagrid/layout.html.twig
            createdAt:
                label: oro.cms.contentwidget.created_at.label
                frontend_type: datetime
            updatedAt:
                label: oro.cms.contentwidget.updated_at.label
                frontend_type: datetime
        sorters:
            columns:
                name:
                    data_name: contentWidget.name
                description:
                    data_name: contentWidget.description
                widgetType:
                    data_name: contentWidget.widgetType
                layout:
                    data_name: contentWidget.layout
                createdAt:
                    data_name: contentWidget.createdAt
                updatedAt:
                    data_name: contentWidget.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                name:
                    type: string
                    data_name: contentWidget.name
                description:
                    type: string
                    data_name: contentWidget.description
                widgetType:
                    type: choice-tree
                    data_name: contentWidget.widgetType
                    autocomplete_alias: oro_cms_content_widget_types
                    renderedPropertyName: 'label'
                createdAt:
                    type: datetime
                    data_name: contentWidget.createdAt
                updatedAt:
                    type: datetime
                    data_name: contentWidget.updatedAt
        properties:
            id: ~
            view_link:
                type: url
                route: oro_cms_content_widget_view
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye
                acl_resource:  oro_cms_content_widget_view
                rowAction:     true

    cms-inline-content-widget-grid:
        extends: cms-content-widget-grid
        source:
            query:
                where:
                    and:
                        - contentWidget.widgetType IN (:contentWidgetTypes)
            bind_parameters:
                - contentWidgetTypes

    cms-block-content-widget-grid:
        extends: cms-content-widget-grid
        source:
            query:
                where:
                    and:
                        - contentWidget.widgetType IN (:contentWidgetTypes)
            bind_parameters:
                - contentWidgetTypes

    cms-content-widget-pages-grid:
        extends: cms-page-grid
        source:
            query:
                join:
                    inner:
                        -
                            join: 'Oro\Bundle\CMSBundle\Entity\ContentWidgetUsage'
                            alias: contentWidgetUsage
                            conditionType: WITH
                            condition: "contentWidgetUsage.contentWidget = :content_widget_id AND contentWidgetUsage.entityClass = '%oro_cms.entity.page.class%' AND contentWidgetUsage.entityId = page.id"
            bind_parameters:
                - content_widget_id

    cms-content-widget-content-blocks-grid:
        extends: cms-content-block-grid
        source:
            query:
                join:
                    inner:
                        - { join: contentBlock.contentVariants, alias: contentVariant }
                        -
                            join: 'Oro\Bundle\CMSBundle\Entity\ContentWidgetUsage'
                            alias: contentWidgetUsage
                            conditionType: WITH
                            condition: "contentWidgetUsage.contentWidget = :content_widget_id AND contentWidgetUsage.entityClass = 'Oro\\Bundle\\CMSBundle\\Entity\\TextContentVariant' AND contentWidgetUsage.entityId = contentVariant.id"
                groupBy: contentBlock.id
            bind_parameters:
                - content_widget_id
        columns:
            enabled:
                renderable: false
            createdAt:
                renderable: false
            updatedAt:
                renderable: false
        filters:
            columns:
                enabled:
                    enabled: false
                createdAt:
                    enabled: false
                updatedAt:
                    enabled: false
