services:
    oro_promotion.form.type.coupon:
        class: 'Oro\Bundle\PromotionBundle\Form\Type\CouponType'
        tags:
            - { name: form.type, alias: oro_promotion_coupon_type  }

    oro_promotion.form.type.coupon_mass_edit:
        class: 'Oro\Bundle\PromotionBundle\Form\Type\BaseCouponType'
        tags:
            - { name: form.type, alias: oro_promotion_base_coupon_type  }

    oro_promotion.form.type.coupon_generate:
        class: 'Oro\Bundle\PromotionBundle\Form\Type\CouponGenerationType'
        arguments:
            - '@oro_security.token_accessor'
        tags:
            - { name: form.type, alias: oro_promotion_coupon_generation_type  }
