config:
    paths:
        'oropromotion/js/app/views/discount-options-view': 'bundles/oropromotion/js/app/views/discount-options-view.js'
        'oropromotion/js/app/views/type-value-switcher': 'bundles/oropromotion/js/app/views/type-value-switcher.js'
        'oropromotion/js/app/views/coupon-generation-preview-view': 'bundles/oropromotion/js/app/views/coupon-generation-preview-view.js'
        'oropromotion/js/app/components/order-line-item-discounts-tax-component': 'bundles/oropromotion/js/app/components/order-line-item-discounts-tax-component.js'
        'oropromotion/js/app/components/order-line-item-discounts-no-tax-component': 'bundles/oropromotion/js/app/components/order-line-item-discounts-no-tax-component.js'
