dynamic-imports:
    orowebcatalog:
        - orowebcatalog/js/app/components/content-variant-collection-component
        - orowebcatalog/js/app/views/default-variant-collection-view
        - orowebcatalog/js/app/views/variants-collection-view
        - orowebcatalog/js/app/views/web-catalog-tree-view
