parameters:
    oro_fedex_shipping.integration.channel.type: 'fedex'
    oro_fedex_shipping.integration.transport.type: 'fedex'
    oro_fedex_shipping.shipping_rule.method_template: 'OroFedexShippingBundle::FedexMethodWithOptions.html.twig'

services:
    oro_fedex_shipping.integration.channel:
        class: 'Oro\Bundle\FedexShippingBundle\Integration\FedexChannel'
        public: false
        tags:
            - { name: oro_integration.channel, type: '%oro_fedex_shipping.integration.channel.type%' }

    oro_fedex_shipping.integration.transport:
        class: 'Oro\Bundle\FedexShippingBundle\Integration\FedexTransport'
        public: false
        tags:
            - { name: oro_integration.transport, type: '%oro_fedex_shipping.integration.transport.type%', channel_type: '%oro_fedex_shipping.integration.channel.type%' }

    oro_fedex_shipping.integration.identifier_generator:
        parent: oro_integration.generator.prefixed_identifier_generator
        arguments:
            - '%oro_fedex_shipping.integration.channel.type%'

