features:
    guest_quote:
        label: oro.sale.system_configuration.fields.enable_guest_quote.label
        description: oro.sale.form.tooltip.enable_guest_quote
        toggle: oro_sale.enable_guest_quote
        routes:
            - oro_sale_quote_frontend_guest_access
