services:
    oro_catalog.api.frontend.category_per_organization_query_modifier:
        class: Oro\Bundle\CatalogBundle\Api\CategoryPerOrganizationQueryModifier
        arguments:
            - '@oro_entity.orm.entity_class_resolver'
            - '@oro_website.manager'
        tags:
            - { name: oro.api.query_modifier, requestType: frontend }

    oro_catalog.api.compute_category_urls:
        class: Oro\Bundle\RedirectBundle\Api\Processor\ComputeUrlFields
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_locale.helper.localization'
            - '@oro_config.manager'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, collection: true, class: Oro\Bundle\CatalogBundle\Entity\Category }

    oro_catalog.api.compute_category_images:
        class: Oro\Bundle\CatalogBundle\Api\Processor\ComputeCategoryImages
        arguments:
            - '@oro_attachment.manager'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, collection: true, class: Oro\Bundle\CatalogBundle\Entity\Category }

    oro_catalog.api.compute_category_path:
        class: Oro\Bundle\CatalogBundle\Api\Processor\ComputeCategoryPath
        arguments:
            - '@oro_api.entity_serializer'
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, collection: true, class: Oro\Bundle\CatalogBundle\Entity\Category }

    oro_catalog.api.subresource.add_parent_entity_id_to_query:
        class: Oro\Bundle\CatalogBundle\Api\Processor\AddParentEntityIdToCategoryQuery
        arguments:
            - '@stof_doctrine_extensions.listener.tree'
            - '@doctrine'
        tags:
            - { name: oro.api.processor, action: get_subresource, group: build_query, priority: -140, requestType: frontend, class: Oro\Bundle\CatalogBundle\Entity\Category, association: categoryPath }
            - { name: oro.api.processor, action: get_relationship, group: build_query, priority: -140, requestType: frontend, class: Oro\Bundle\CatalogBundle\Entity\Category, association: categoryPath }

    oro_catalog.api.hide_invisible_product_category:
        class: Oro\Bundle\CatalogBundle\Api\Processor\HideInvisibleProductCategories
        arguments:
            - '@oro_api.entity_serializer.query_factory'
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, collection: true, requestType: frontend, class: Oro\Bundle\ProductBundle\Entity\Product }
