services:
    # Twig extensions
    oro_catalog.twig.category_extension:
        class: 'Oro\Bundle\CatalogBundle\Twig\CategoryExtension'
        public: false
        arguments:
            - '@Psr\Container\ContainerInterface'
        tags:
            - { name: twig.extension }
            - { name: container.service_subscriber }

    oro_catalog.twig.category_image_extension:
        class: 'Oro\Bundle\CatalogBundle\Twig\CategoryImageExtension'
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }
