config:
    paths:
        'oroconsent/js/app/views/consent-entity-tree-select-form': 'bundles/oroconsent/js/app/views/consent-entity-tree-select-form.js'
        'oroconsent/js/app/views/consent-update-content-nodes-view': 'bundles/oroconsent/js/app/views/consent-update-content-nodes-view.js'
