api:
    entities:
        Oro\Bundle\OrderBundle\Entity\Order:
            documentation_resource: '@OroPromotionBundle/Resources/doc/api/order.md'
            fields:
                discount:
                    data_type: float
                    property_path: _
                shippingDiscount:
                    data_type: float
                    property_path: _
            actions:
                create:
                    fields:
                        discount:
                            exclude: true
                        shippingDiscount:
                            exclude: true
                update:
                    fields:
                        discount:
                            exclude: true
                        shippingDiscount:
                            exclude: true
