aliases:
    grapesjs$: npmassets/grapesjs/dist/grapes
    grapesjs-preset-webpage$: npmassets/grapesjs-preset-webpage/dist/grapesjs-preset-webpage.min
dynamic-imports:
    orocms:
        - orocms/js/app/components/content-variant-collection-component
        - orocms/js/app/grapesjs/grapesjs-editor-view
        - orocms/js/app/views/content-widget-view
        - orocms/js/app/views/default-variant-collection-view
        - orocms/js/app/views/variants-collection-view
        - orocms/js/app/grapesjs/helpers/digital-asset-helper
        - orocms/js/app/grapesjs/components/digital-assets
        - orocms/js/app/grapesjs/components/digital-asset-image
        - orocms/js/app/grapesjs/components/digital-asset-file
        - orocms/js/app/grapesjs/components/digital-asset-property-file-type
