config:
    paths:
        'grapesjs': 'bundles/npmassets/grapesjs/dist/grapes.js'
        'grapesjs-preset-webpage': 'bundles/npmassets/grapesjs-preset-webpage/dist/grapesjs-preset-webpage.min.js'
        'orocms/js/app/views/grapesjs-editor-view': 'bundles/orocms/js/app/views/grapesjs-editor-view.js'

        'orocms/js/app/views/grapesjs-modules/grapesjs-modules': 'bundles/orocms/js/app/views/grapesjs-modules/grapesjs-modules.js'
        'orocms/js/app/views/grapesjs-modules/style-manager-module': 'bundles/orocms/js/app/views/grapesjs-modules/style-manager-module.js'
        'orocms/js/app/views/grapesjs-modules/panels-module': 'bundles/orocms/js/app/views/grapesjs-modules/panels-module.js'
        'orocms/js/app/views/grapesjs-modules/grapesjs-devices-module': 'bundles/orocms/js/app/views/grapesjs-modules/grapesjs-devices-module.js'
        'orocms/js/app/views/grapesjs-modules/grapesjs-extension': 'bundles/orocms/js/app/views/grapesjs-modules/grapesjs-extension.js'
        'orocms/js/app/views/grapesjs-modules/grapesjs-components': 'bundles/orocms/js/app/views/grapesjs-modules/grapesjs-components.js'
        'orocms/js/app/views/grapesjs-modules/controls/theme-selector-view': 'bundles/orocms/js/app/views/grapesjs-modules/controls/theme-selector-view.js'
        'orocms/js/app/views/grapesjs-modules/components/table': 'bundles/orocms/js/app/views/grapesjs-modules/components/table.js'
        'orocms/js/app/views/grapesjs-modules/components/table-responsive': 'bundles/orocms/js/app/views/grapesjs-modules/components/table-responsive.js'

        'orocms/js/app/components/content-variant-collection-component': 'bundles/orocms/js/app/components/content-variant-collection-component.js'
        'orocms/js/app/views/variants-collection-view': 'bundles/orocms/js/app/views/variants-collection-view.js'
        'orocms/js/app/views/default-variant-collection-view': 'bundles/orocms/js/app/views/default-variant-collection-view.js'
        'orocms/js/app/views/content-widget-view': 'bundles/orocms/js/app/views/content-widget-view.js'
