parameters:
    oro_cms.entity.page.class: Oro\Bundle\CMSBundle\Entity\Page
    oro_cms.entity.content_block.class: Oro\Bundle\CMSBundle\Entity\ContentBlock
    oro_cms.entity.loginpage.class: Oro\Bundle\CMSBundle\Entity\LoginPage

services:
    oro_cms.form.autocomplete.page.search_handler:
        public: false
        parent: oro_form.autocomplete.search_handler
        arguments:
            - '%oro_cms.entity.page.class%'
            - [ "defaultTitle.string"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: Oro\Bundle\CMSBundle\Form\Type\PageType, acl_resource: oro_cms_page_view }

    oro_cms.provider.login_page_data_provider:
        class: 'Oro\Bundle\CMSBundle\Layout\DataProvider\LoginPageProvider'
        arguments:
            - "@doctrine"
        calls:
            - [setLoginPageClass, ['%oro_cms.entity.loginpage.class%']]
        tags:
            - { name: layout.data_provider, alias: oro_cms_login_page }

    oro_cms.content_block.resolver:
        class: 'Oro\Bundle\CMSBundle\ContentBlock\ContentBlockResolver'
        arguments:
            - "@property_accessor"

    oro_cms.content_block.default_content_variant_scopes_resolver:
        class: 'Oro\Bundle\CMSBundle\ContentBlock\DefaultContentVariantScopesResolver'
        public: false

    oro_cms.provider.content_block_provider:
        class: 'Oro\Bundle\CMSBundle\Layout\DataProvider\ContentBlockDataProvider'
        arguments:
            - "@oro_cms.content_block.resolver"
            - "@doctrine"
            - "@oro_scope.scope_manager"
            - "@logger"
            - "%oro_cms.entity.content_block.class%"
            - "cms_content_block"
        tags:
            - { name: layout.data_provider, alias: content_block }
            - { name: monolog.logger, channel: oro_cms }

    oro_cms.content_variant_type.cms_page:
        class: Oro\Bundle\CMSBundle\ContentVariantType\CmsPageContentVariantType
        public: false
        arguments:
            - '@security.authorization_checker'
            - '@property_accessor'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_cms.provider.routing_information_provider:
        class: Oro\Bundle\CMSBundle\Provider\PageRoutingInformationProvider
        arguments:
            - '@oro_config.global'
        tags:
            - { name: oro_redirect.routing_information_provider, alias: '%oro_cms.entity.page.class%' }

    oro_cms.config.event_listener.direct_url_prefix_change:
        class: Oro\Bundle\RedirectBundle\EventListener\ConfigRegenerateDirectUrlListener
        arguments:
            - '@oro_config.manager'
            - '@oro_message_queue.client.message_producer'
            - '@oro_redirect.form.storage.redirect_storage'
            - '@oro_redirect.direct_url_message_factory'
            - 'oro_cms.landing_page_direct_url_prefix'
            - '%oro_cms.entity.page.class%'
        tags:
            - { name: kernel.event_listener, event: oro_config.update_after, method: onUpdateAfter }

    oro_cms.localization_scope_criteria_provider:
        class: 'Oro\Bundle\LocaleBundle\Provider\LocalizationScopeCriteriaProvider'
        public: false
        arguments:
            - "@oro_locale.provider.current_localization"
        tags:
            - { name: oro_scope.provider, scopeType: cms_content_block, priority: 1 }

    oro_cms.twig.content_security_policy:
        class: 'Twig_Sandbox_SecurityPolicy'
        public: false
        arguments:
            # tags
            - []
            # filters
            - ['escape']
            # methods
            - []
            # properties
            - []
            # functions
            - ['widget', 'content_block']

    oro_cms.twig.sandbox_extension:
        class: 'Twig_Extension_Sandbox'
        arguments:
            - '@oro_cms.twig.content_security_policy'
            - true # use sandbox globally in instance
        public: false

    oro_cms.twig.widget_extension:
        class: 'Oro\Bundle\CMSBundle\Twig\WidgetExtension'
        arguments:
            - '@oro_cms.content_widget.renderer'

    oro_cms.twig.content_widget_type_extension:
        class: 'Oro\Bundle\CMSBundle\Twig\ContentWidgetTypeExtension'
        arguments:
            - '@translator'
            - '@oro_cms.content_widget.type_registry'
        tags:
            - { name: twig.extension }

    oro_cms.twig.content_block_extension:
        class: 'Oro\Bundle\CMSBundle\Twig\ContentBlockExtension'
        arguments:
            - '@oro_cms.content_block.renderer'
        tags:
            - { name: twig.extension }

    oro_cms.twig.array_loader:
        class: 'Twig\Loader\ArrayLoader'

    oro_cms.twig.renderer:
        class: 'Twig\Environment'
        arguments:
            - '@oro_cms.twig.array_loader'
        calls:
            - [addExtension, ['@oro_cms.twig.widget_extension']]
            - [addExtension, ['@oro_cms.twig.content_block_extension']]
            - [addExtension, ['@oro_cms.twig.sandbox_extension']]

    oro_crm.twig.twig_in_variables_extension:
        class: 'Oro\Bundle\CMSBundle\Twig\TwigInVariablesExtension'
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    oro_cms.migration.home_page_slider_images_source_fixer:
        class: 'Oro\Bundle\CMSBundle\Migration\HomePageSliderImagesSourceFixer'
        # This service marked as public for compatibility with Symfony 4. All dependencies must be refactored after BAP-17037
        public: true
        arguments:
            - '@oro_config.global'
            - '@doctrine.dbal.default_connection'

    oro_cms.entity_listener.page:
        class: Oro\Bundle\CMSBundle\Entity\EntityListener\PageEntityListener
        public: false
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_message_queue.message_producer'
        tags:
            - { name: doctrine.orm.entity_listener, entity: '%oro_cms.entity.page.class%', event: preRemove }
            - { name: doctrine.orm.entity_listener, entity: '%oro_cms.entity.page.class%', event: postRemove }

    oro_cms.parser.twig_content_widget:
        class: Oro\Bundle\CMSBundle\Parser\TwigContentWidgetParser
        arguments:
            - '@oro_cms.twig.renderer'

    oro_cms.entity_listener.page_content:
        class: Oro\Bundle\CMSBundle\Entity\EntityListener\PageContentEntityListener
        arguments:
            - '@oro_cms.parser.twig_content_widget'
            - '@oro_entity.doctrine_helper'
            - '@property_accessor'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\CMSBundle\Entity\Page', event: postPersist }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\CMSBundle\Entity\Page', event: preUpdate }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\CMSBundle\Entity\Page', event: preRemove }

    oro_cms.entity_listener.text_content_variant_content:
        class: Oro\Bundle\CMSBundle\Entity\EntityListener\TextContentVariantEntityListener
        arguments:
            - '@oro_cms.parser.twig_content_widget'
            - '@oro_entity.doctrine_helper'
            - '@property_accessor'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\CMSBundle\Entity\TextContentVariant', event: postPersist }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\CMSBundle\Entity\TextContentVariant', event: preUpdate }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\CMSBundle\Entity\TextContentVariant', event: preRemove }

    oro_cms.content_widget.type_registry:
        class: Oro\Bundle\CMSBundle\ContentWidget\ContentWidgetTypeRegistry
        arguments:
            - !tagged oro_cms.content_widget.type

    Oro\Bundle\CMSBundle\ContentWidget\ContentWidgetTypeRegistry:
        alias: oro_cms.content_widget.type_registry

    oro_cms.autocomplete.content_widget_type.search_handler:
        class: Oro\Bundle\CMSBundle\Autocomplete\ContentWidgetTypeSearchHandler
        arguments:
            - '@oro_cms.content_widget.type_registry'
            - '@translator'
            - '@property_accessor'
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: 'oro_cms_content_widget_types' }

    oro_cms.provider.content_widget_type:
        class: Oro\Bundle\CMSBundle\Provider\ContentWidgetTypeProvider
        public: true
        arguments:
            - '@oro_cms.content_widget.type_registry'
            - '@translator'

    oro_cms.acl.voter.frontend_quote_permission_voter:
        class: Oro\Bundle\CMSBundle\Acl\Voter\ContentWidgetVoter
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: security.voter }

    oro_cms.content_block.renderer:
        class: Oro\Bundle\CMSBundle\ContentBlock\ContentBlockRenderer
        arguments:
            - '@oro_cms.provider.content_block_provider'
            - '@twig'
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: monolog.logger, channel: oro_cms }

    oro_cms.content_widget.renderer:
        class: Oro\Bundle\CMSBundle\ContentWidget\ContentWidgetRenderer
        arguments:
            - '@oro_cms.content_widget.type_registry'
            - '@doctrine'
            - '@twig'
        calls:
            - [setTokenAccessor, ['@oro_security.token_accessor']]
            - [setLogger, ['@logger']]
        tags:
            - { name: monolog.logger, channel: oro_cms }

    oro_cms.entity_config_dumper.extension.wysiwyg:
        class: Oro\Bundle\CMSBundle\Tools\DumperExtensions\WYSIWYGEntityConfigDumperExtension
        arguments:
            - '@oro_entity_config.config_manager'
            - '@oro_bundle_cms.helper.wysiwygschema'
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension, priority: -257 }

    oro_cms.listener.wysiwyg_serialized_config:
        class: Oro\Bundle\CMSBundle\EventListener\WYSIWYGSerializedConfigListener
        arguments:
            - '@oro_bundle_cms.helper.wysiwygschema'
        tags:
            - { name: kernel.event_listener, event: oro.entity_config.pre_flush, method: preFlush, priority: 255 }

    oro_cms.event_listener.content_widget_datagrid:
        class: Oro\Bundle\CMSBundle\EventListener\ContentWidgetDatagridListener
        arguments:
            - '@oro_cms.content_widget.type_registry'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre.cms-content-widget-grid, method: onPreBuild }
            - { name: kernel.event_listener, event: oro_datagrid.orm_datasource.result.after.cms-content-widget-grid, method: onResultAfter }

    oro_bundle_cms.helper.wysiwygschema:
        class: Oro\Bundle\CMSBundle\Helper\WYSIWYGSchemaHelper
        arguments:
            - '@oro_entity_config.config_manager'

    oro_cms.attribute_type.wysiwyg:
        class: Oro\Bundle\CMSBundle\Attribute\Type\WYSIWYGAttributeType
        public: false
        arguments:
            - '@oro_ui.html_tag_helper'
        tags:
             - { name: oro_entity_config.attribute_type }

    oro_cms.form.type.wysiwyg:
        class: Oro\Bundle\CMSBundle\Form\Type\WYSIWYGType
        arguments:
            - '@oro_form.provider.html_tag_provider'
        tags:
            - { name: form.type }

    oro_cms.validator.wysiwyg:
        class: Oro\Bundle\CMSBundle\Validator\Constraints\WYSIWYGValidator
        arguments:
            - '@oro_ui.html_tag_helper'
            - '@logger'
        tags:
            - { name: validator.constraint_validator, alias: wysiwyg_validator }

    oro_cms.provider.html_purifier_scope_provider:
        class: Oro\Bundle\CMSBundle\Provider\HTMLPurifierScopeProvider
        public: false
        arguments:
            - '@oro_security.token_accessor'
            - '%oro_cms.content_restrictions_mode%'
            - '%oro_cms.lax_content_restrictions%'
        calls:
            - [addScopeMapping, ['secure', 'default']]
            - [addScopeMapping, ['selective', 'lax']]
            - [addScopeMapping, ['unsecure', null]]
