Oro\Bundle\CMSBundle\Entity\Page:
    properties:
        organization:
            - NotBlank: ~
        titles:
            - Valid: ~
        slugPrototypes:
            - Valid: ~

Oro\Bundle\CMSBundle\Entity\ContentBlock:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: alias
    properties:
        alias:
            - NotBlank: ~
            - Regex:
                pattern: '/^[a-zA-Z0-9_\-]*$/'
                message: oro.cms.contentblock.alias.regex.message
        titles:
            - NotBlank: ~
            - Valid: ~
        scopes:
            - Oro\Bundle\CustomerBundle\Validator\Constraints\ScopeWithCustomerGroupAndCustomer: ~
        contentVariants:
            - Valid: ~

Oro\Bundle\CMSBundle\Entity\ContentWidget:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [organization, name]
    properties:
        name:
            - NotBlank: ~
            - Length:
                  max: 255
        widgetType:
            - NotBlank: ~
            - Length:
                  max: 255
        template:
            - Length:
                  max: 255
        organization:
            - NotBlank: ~

Oro\Bundle\CMSBundle\Entity\ImageSlide:
    properties:
        contentWidget:
            - NotBlank: ~
        order:
            - NotBlank: ~
        url:
            - NotBlank: ~
            - Length:
                  max: 255
        displayInSameWindow:
            - NotBlank: ~
        title:
            - NotBlank: ~
            - Length:
                  max: 255
        text:
            - Length:
                  max: 255
        mainImage:
            - NotBlank: ~
        organization:
            - NotBlank: ~

Oro\Bundle\CMSBundle\Entity\TextContentVariant:
    properties:
        scopes:
            - Oro\Bundle\CustomerBundle\Validator\Constraints\ScopeWithCustomerGroupAndCustomer: ~
