layout:
    imports:
        -
            id: matrix_grid_order
            root: __root
            namespace: matrix
    actions:
        - '@setBlockTheme':
            themes: 'product_list_matrix_grid_order.html.twig'
        - '@setOption':
            id: __matrix_wrapper
            optionName: form
            optionValue: '=data["oro_shopping_list_matrix_order_form"].getMatrixOrderFormView(product, shoppingList)'
