services:
    Oro\Bundle\PricingBundle\Command\CombinedPriceListScheduleCommand:
        public: false
        class: Oro\Bundle\PricingBundle\Command\CombinedPriceListScheduleCommand
        tags:
            - { name: console.command }

    Oro\Bundle\PricingBundle\Command\PriceListImportCommand:
        public: false
        class: Oro\Bundle\PricingBundle\Command\PriceListImportCommand
        arguments:
            - '@oro_importexport.file.file_manager'
            - '@oro_importexport.handler.import'
            - '@oro_message_queue.client.message_producer'
        tags:
            - { name: console.command }

    Oro\Bundle\PricingBundle\Command\PriceListRecalculateCommand:
        public: false
        class: Oro\Bundle\PricingBundle\Command\PriceListRecalculateCommand
        tags:
            - { name: console.command }

    Oro\Bundle\PricingBundle\Command\PriceListStorageReorganizeCommand:
        public: false
        class: Oro\Bundle\PricingBundle\Command\PriceListStorageReorganizeCommand
        tags:
            - { name: console.command }
