services:
    oro_pricing.api.handle_price_list_status_change:
        class: Oro\Bundle\PricingBundle\Api\PriceList\Processor\HandlePriceListStatusChange
        arguments:
            - '@oro_pricing.price_list_relation_trigger_handler'
        tags:
            - { name: oro.api.processor, action: update, group: load_data, class: Oro\Bundle\PricingBundle\Entity\PriceList, priority: -100 }
            - { name: oro.api.processor, action: update, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceList, priority: -40 }

    oro_pricing.api.update_price_list_lexemes:
        class: Oro\Bundle\PricingBundle\Api\PriceList\Processor\UpdatePriceListLexemes
        arguments:
            - '@oro_pricing.hander.price_rule_lexeme_handler'
        tags:
            - { name: oro.api.processor, action: update, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceList, priority: -40 }
            - { name: oro.api.processor, action: create, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceList, priority: -40 }

    oro_pricing.api.build_combined_price_list:
        class: Oro\Bundle\PricingBundle\Api\PriceListSchedule\Processor\BuildCombinedPriceList
        arguments:
            - '@oro_pricing.builder.combined_price_list_activation_plan_builder'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceListSchedule, priority: -40 }
            - { name: oro.api.processor, action: update, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceListSchedule, priority: -40 }

    oro_pricing.api.update_lexemes_price_rule:
        class: Oro\Bundle\PricingBundle\Api\PriceRule\Processor\UpdateLexemesPriceRule
        arguments:
            - '@oro_pricing.hander.price_rule_lexeme_handler'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceRule, priority: -20 }
            - { name: oro.api.processor, action: update, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceRule, priority: -20 }

    oro_pricing.api.update_lexemes_on_price_rule_delete:
        class: Oro\Bundle\PricingBundle\Api\PriceRule\Processor\UpdateLexemesOnPriceRuleDelete
        arguments:
            - '@oro_pricing.hander.price_rule_lexeme_handler'
            - '@oro_api.delete.delete_entity_by_delete_handler'
        tags:
            - { name: oro.api.processor, action: delete, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceRule, priority: 10 }

    oro_pricing.api.update_lexemes_on_price_rule_delete_list:
        class: Oro\Bundle\PricingBundle\Api\PriceRule\Processor\UpdateLexemesOnPriceRuleDeleteList
        arguments:
            - '@oro_pricing.hander.price_rule_lexeme_handler'
            - '@oro_api.delete_list.delete_entities_by_delete_handler'
        tags:
            - { name: oro.api.processor, action: delete_list, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceRule, priority: -15 }

    oro_pricing.api_form_subscriber.add_schedules_to_price_list:
        class: Oro\Bundle\PricingBundle\Api\PriceListSchedule\Form\AddSchedulesToPriceListApiFormSubscriber
        public: true

    oro_pricing.api.save_price_list_schedules_to_context:
        class: Oro\Bundle\PricingBundle\Api\PriceListSchedule\Processor\SavePriceListSchedulesToContext
        tags:
            - { name: oro.api.processor, action: delete, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListSchedule }
            - { name: oro.api.processor, action: delete_list, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListSchedule }

    oro_pricing.api.build_combined_price_lists:
        class: Oro\Bundle\PricingBundle\Api\PriceListSchedule\Processor\BuildCombinedPriceLists
        arguments:
            - '@oro_pricing.builder.combined_price_list_activation_plan_builder'
        tags:
            - { name: oro.api.processor, action: delete, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListSchedule, priority: -40 }
            - { name: oro.api.processor, action: delete_list, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListSchedule, priority: -40 }

    oro_pricing.api.update_price_lists_contain_schedule:
        class: Oro\Bundle\PricingBundle\Api\PriceListSchedule\Processor\UpdatePriceListsContainSchedule
        arguments:
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: delete, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListSchedule, priority: -45 }
            - { name: oro.api.processor, action: delete_list, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListSchedule, priority: -45 }

    oro_pricing.api.remove_price_list_schedules_from_context:
        class: Oro\Bundle\PricingBundle\Api\PriceListSchedule\Processor\RemovePriceListSchedulesFromContext
        tags:
            - { name: oro.api.processor, action: delete, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListSchedule, priority: -50 }
            - { name: oro.api.processor, action: delete_list, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListSchedule, priority: -50 }

    oro_pricing.api.price_list_relation_trigger_handler_for_website_and_customer_group:
        class: Oro\Bundle\PricingBundle\Api\Processor\PriceListRelationTriggerHandlerForWebsiteAndCustomerGroup
        arguments:
            - '@oro_pricing.price_list_relation_trigger_handler'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceListCustomerGroupFallback, priority: -40 }
            - { name: oro.api.processor, action: update, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceListCustomerGroupFallback, priority: -40 }
            - { name: oro.api.processor, action: delete, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListCustomerGroupFallback }
            - { name: oro.api.processor, action: delete_list, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListCustomerGroupFallback }
            - { name: oro.api.processor, action: create, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceListToCustomerGroup, priority: -40 }
            - { name: oro.api.processor, action: update, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceListToCustomerGroup, priority: -40 }
            - { name: oro.api.processor, action: delete, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListToCustomerGroup }
            - { name: oro.api.processor, action: delete_list, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListToCustomerGroup }

    oro_pricing.api.price_list_relation_trigger_handler_for_website_and_customer:
        class: Oro\Bundle\PricingBundle\Api\Processor\PriceListRelationTriggerHandlerForWebsiteAndCustomer
        arguments:
            - '@oro_pricing.price_list_relation_trigger_handler'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceListCustomerFallback, priority: -40 }
            - { name: oro.api.processor, action: update, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceListCustomerFallback, priority: -40 }
            - { name: oro.api.processor, action: delete, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListCustomerFallback }
            - { name: oro.api.processor, action: delete_list, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListCustomerFallback }
            - { name: oro.api.processor, action: create, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceListToCustomer, priority: -40 }
            - { name: oro.api.processor, action: update, group: save_data, class: Oro\Bundle\PricingBundle\Entity\PriceListToCustomer, priority: -40 }
            - { name: oro.api.processor, action: delete, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListToCustomer }
            - { name: oro.api.processor, action: delete_list, group: delete_data, class: Oro\Bundle\PricingBundle\Entity\PriceListToCustomer }

    oro_pricing.api.update_price_by_value_and_currency:
        class: Oro\Bundle\CurrencyBundle\Api\Processor\UpdatePriceByValueAndCurrency
        tags:
            - { name: oro.api.processor, action: customize_form_data, event: pre_submit|post_validate, class: Oro\Bundle\PricingBundle\Entity\ProductPrice }
            - { name: oro.api.processor, action: customize_form_data, event: pre_submit|post_validate, class: Oro\Bundle\PricingBundle\Entity\PriceAttributeProductPrice }

    oro_pricing.api.normalize_product_price_id:
        class: Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\NormalizeInputProductPriceId
        arguments:
            - '@oro_api.doctrine_helper'
            - '@validator'
        tags:
            - { name: oro.api.processor, action: get, group: normalize_input, requestType: rest, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: -120 }
            - { name: oro.api.processor, action: delete, group: normalize_input, requestType: rest, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: -120 }
            - { name: oro.api.processor, action: update, group: normalize_input, requestType: rest, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: -120 }

    oro_pricing.api.normalize_product_price:
        class: Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\NormalizeOutputProductPriceId
        tags:
            - { name: oro.api.processor, action: get, group: finalize, class: Oro\Bundle\PricingBundle\Entity\ProductPrice }
            - { name: oro.api.processor, action: get_list, group: finalize, class: Oro\Bundle\PricingBundle\Entity\ProductPrice }

    oro_pricing.api.set_price_list_in_context_by_product_price:
        class: Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\StorePriceListInContextByProductPrice
        tags:
            - { name: oro.api.processor, action: create, group: save_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice }
            - { name: oro.api.processor, action: update, group: save_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice }

    oro_pricing.update.load_normalized_entity:
        class: Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\LoadNormalizedProductPriceWithNormalizedId
        arguments:
            - '@oro_api.action_processor_bag'
        tags:
            - { name: oro.api.processor, action: update, group: normalize_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice}
            - { name: oro.api.processor, action: create, group: normalize_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice}

    oro_pricing.api.handle_price_list_filter:
        class: Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\HandlePriceListFilter
        arguments:
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_input, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: -120 }
            - { name: oro.api.processor, action: delete_list, group: normalize_input, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: -120 }

    oro_pricing.api.build_single_item_query:
        class: Oro\Bundle\ApiBundle\Processor\Shared\BuildSingleItemQuery
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_api.entity_id_helper'
        tags:
            - { name: oro.api.processor, action: update, group: load_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: 10 }
            - { name: oro.api.processor, action: delete, group: load_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: 10 }

    oro_pricing.api.load_entity_by_orm_query:
        class: Oro\Bundle\ApiBundle\Processor\Shared\LoadEntityByOrmQuery
        arguments:
            - '@oro_entity.query_hint_resolver'
        tags:
            - { name: oro.api.processor, action: update, group: load_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice }
            - { name: oro.api.processor, action: delete, group: load_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice }

    oro_pricing.api.enabled_price_sharding_on_query:
        class: Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\EnableShardingOnQuery
        arguments:
            - '@oro_pricing.shard_manager'
        tags:
            - { name: oro.api.processor, action: update, group: load_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: 5 }
            - { name: oro.api.processor, action: delete, group: load_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: 5 }
            - { name: oro.api.processor, action: delete_list, group: build_query, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: -255 }

    oro_pricing.api.enable_price_sharding_on_config:
        class: Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\EnableShardingOnConfig
        arguments:
            - '@oro_pricing.shard_manager'
        tags:
            - { name: oro.api.processor, action: get_list, group: build_query, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: -255 }
            - { name: oro.api.processor, action: get, group: build_query, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: -255 }

    oro_pricing.api.save_product_price:
        class: Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\SaveProductPrice
        arguments:
            - '@oro_pricing.manager.price_manager'
        tags:
            - { name: oro.api.processor, action: update, group: save_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: -5 }
            - { name: oro.api.processor, action: create, group: save_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: -5 }

    oro_pricing.api.remember_product_price:
        class: Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\RememberProductPrice
        tags:
            - { name: oro.api.processor, action: update, group: load_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice, priority: -45 }

    oro_pricing.api.reset_price_rule_field:
        class: Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\ResetPriceRuleField
        tags:
            - { name: oro.api.processor, action: update, group: save_data, class: Oro\Bundle\PricingBundle\Entity\ProductPrice }

    oro_pricing.api.compute_product_prices:
        class: Oro\Bundle\PricingBundle\Api\Processor\ComputeProductPrices
        arguments:
            - '@oro_pricing.storage.prices'
            - '@oro_pricing.model.product_price_scope_criteria_factory'
            - '@oro_customer.provider.customer_user_relations_provider'
            - '@oro_pricing.user_currency_manager'
            - '@security.token_storage'
            - '@oro_website.manager'
            - '@oro_api.doctrine_helper'
            - '@oro_api.value_transformer'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, collection: true, requestType: frontend, class: Oro\Bundle\ProductBundle\Entity\Product }

    oro_pricing.api.product_search.update_depends_on_config_for_minimal_price_field:
        class: Oro\Bundle\PricingBundle\Api\Processor\UpdateDependsOnConfigForMinimalPriceField
        arguments:
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: get_list, group: build_query, requestType: frontend, class: Oro\Bundle\ProductBundle\Api\Model\ProductSearch, priority: -85 }

    oro_pricing.api.product_search.compute_minimal_prices:
        class: Oro\Bundle\PricingBundle\Api\Processor\ComputeProductSearchMinimalPrices
        arguments:
            - '@oro_api.value_transformer'
            - '@oro_pricing.user_currency_manager'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, class: Oro\Bundle\ProductBundle\Api\Model\ProductSearch }
