security:
    firewalls:
        shoppinglist:
            pattern:                 ^/customer/shoppinglist
            context:                 customer_identity
            anonymous_customer_user: true
        shopping_list_api:
            pattern:    ^/api/rest/(v1|latest)/entity_data/(Oro_Bundle_ShoppingListBundle_Entity_ShoppingList|Oro_Bundle_ShoppingListBundle_Entity_LineItem)/\d+$
            context: customer_identity
            anonymous_customer_user: true
